// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Gv7pdnm2wnazQ3Ja0GuUtRnHy6ZPxPQ',
    appId: '1:453950730767:web:059da8f89e14d87c61297a',
    messagingSenderId: '453950730767',
    projectId: 'primer-proyecto-7054d',
    authDomain: 'primer-proyecto-7054d.firebaseapp.com',
    storageBucket: 'primer-proyecto-7054d.appspot.com',
    measurementId: 'G-PPH1SCRY0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW3Dr5iK2LIjmRMgB80h3EUhoMzu-1L90',
    appId: '1:453950730767:android:94d70136cb16500861297a',
    messagingSenderId: '453950730767',
    projectId: 'primer-proyecto-7054d',
    storageBucket: 'primer-proyecto-7054d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhAt44tzFz4xMBS9bI_O4wZ5EX34qmXe0',
    appId: '1:453950730767:ios:0df423718bbce26661297a',
    messagingSenderId: '453950730767',
    projectId: 'primer-proyecto-7054d',
    storageBucket: 'primer-proyecto-7054d.appspot.com',
    iosBundleId: 'com.example.appfirebase',
  );
}
